server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ajax_test
    username: root
    password: ok

mybatis:
  mapper-locations: mapper/*.xml
